version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image: city-pass
    build:
      context: ./city-pass
      dockerfile: Dockerfile
    hostname: city-pass
    restart: always
    logging: *default-logging